# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - '*'

jobs:
  build_onejar_fabric_1_16_5:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd onejar && cd fabric_1_16_5 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_onejar_fabric_1_16_5"
        path: build/libs/
  build_onejar_fabric_1_20_1:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd onejar && cd fabric_1_20_1 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_onejar_fabric_1_20_1"
        path: build/libs/
  build_onejar_fabric_1_21_6:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd onejar && cd fabric_1_21_6 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_onejar_fabric_1_21_6"
        path: build/libs/
  build_onejar_fabric_1_21_11:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd onejar && cd fabric_1_21_11 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_onejar_fabric_1_21_11"
        path: build/libs/
  # build_onejar_neoforge_1_21_6:
  #   runs-on: windows-latest
  #   permissions:
  #     contents: read
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     with:
  #       submodules: 'true'
  #   - name: Set up JDK 21
  #     uses: actions/setup-java@v4
  #     with:
  #       java-version: '21'
  #       distribution: 'temurin'
  #   - name: Setup Gradle
  #     uses: gradle/actions/setup-gradle@v3 # v3.1.0
  #   - name: build
  #     shell: cmd
  #     run: |
  #       link.cmd && cd onejar && cd neoforge_1_21_6 && gradlew build
  #   - name: update
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: "allmusic_onejar_neoforge_1_21_6"
  #       path: build/libs/